# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-26 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
